#pragma once

#define SERVICE_CLS 0
#define SERVICE_PRINT_TEXT 1
#define SERVICE_PRINT_WORD 2
#define SERVICE_STRLEN 3
#define SERVICE_INPUT_EMPTY 4
#define SERVICE_INPUT_READ 5
#define SERVICE_STRCMP 6
#define SERVICE_STRNCMP 7
#define SERVICE_NEWLINE 8
#define SERVICE_RNG 9
#define SERVICE_GPU_BLOCK 10
#define SERVICE_GPU_BYTE 11
#define SERVICE_GPU_FLUSH 12
#define SERVICE_TIMER 13
#define SERVICE_LIST_DIR 14
#define SERVICE_LIST_NEXT 15
#define SERVICE_OPEN_FILE 16
#define SERVICE_READ_FILE 17
#define SERVICE_CLOSE_FILE 18
#define SERVICE_BOUNDS_CHECK 19